# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'events',
            },
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['event__name', 'date_time']},
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='publication_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='publication_reference',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='publication_url',
            new_name='url',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meetings.Event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='category',
            field=models.ManyToManyField(blank=True, to='meetings.Category'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
